### ISSUE TITLE
Despawn timer modify failure and solution (1.20.2)

### ISSUE THREAD

**Issue by lota09** [ps-dps/KeepSomeInventory#10]
In spawn_next.mcfunction,

`
execute store result entity @e[type=item, tag=ps-keep, limit=1] Age short 1 run scoreboard players get item_despawn_offset[-32768_to_5999] config_ps-keep
`

`config_ps-keep` is unknown scoreboard objective.
correct it to `ps-keep.config` like below.

`
execute store result entity @e[type=item, tag=ps-keep, limit=1] Age short 1 run scoreboard players get item_despawn_offset[-32768_to_5999] ps-keep.config
`

**Comment by PuckiSilver** [comment]
Hey, thanks for pointing that out!
Just fixed it, will be released within the next minutes! :)
https://github.com/ps-dps/KeepSomeInventory/commit/d6c872fb37ff8779a98fb50ef01487a2efeb3ffa

**Comment by PuckiSilver** [comment]
They are released! Closing this
https://modrinth.com/datapack/keep-some-inventory/version/v1.3.2
https://modrinth.com/datapack/keep-some-inventory/version/v1.3.2+mod

**Comment by lota09** [comment]
It's very nice to see my(and my ChatGPT's) product of hard work to find the problem
I am not a mod developer, just a gamer :)
So i spend few hours to study commands and find the problem.
RIP my 23 diamonds anyway... hehe

**Comment by PuckiSilver** [comment]
Okay, actually, I fixed it in the wrong way 🤦 
Will quickly push another fix ^^

_(and RIP to your diamonds, they will be missed 😢)_

**Comment by PuckiSilver** [comment]
Here is the actual fix, sorry :D
https://modrinth.com/datapack/keep-some-inventory/version/v1.3.3
https://modrinth.com/datapack/keep-some-inventory/version/v1.3.3+mod
