### ISSUE TITLE
Keep inventory is set to true even after removing mod

### ISSUE THREAD

**Issue by ManicQuinn** [ps-dps/KeepSomeInventory#11]
So, if this mod requires KeepInv set to true, makes sense that removing it didn't change it back, but I was not informed of this, so I spent like 15 minutes trying to figure it out lol

Should be added that the gamerule should be changed back if you uninstall the mod.

**Comment by PuckiSilver** [comment]
Because the mod is made as a data pack, that is not possible, uninstalling the mod is literally removing all of its files, there is no way to  do this.

**Comment by ManicQuinn** [comment]
No, I was saying it should be added as a disclaimer of how to properly uninstall it, I was not aware of it and I'm sure a ton of others aren't either

**Comment by PuckiSilver** [comment]
And where would that disclaimer be?
I don't think everyone needs to see it, I don't think there are many people that uninstall mods and keep playing in the same world, so showing it on first install or reload is overkill

And, if you uninstall the mod, I don't think you will check back to a README or the config function

Keeping this as a "Won't Fix" unless you have a great idea that I didn't think of

**Comment by ManicQuinn** [comment]
> And where would that disclaimer be? I don't think everyone needs to see it, I don't think there are many people that uninstall mods and keep playing in the same world, so showing it on first install or reload is overkill
> 
> And, if you uninstall the mod, I don't think you will check back to a README or the config function
> 
> Keeping this as a "Won't Fix" unless you have a great idea that I didn't think of

You could put it in the description of the Mod on Modrinth or any other docs?
