### ISSUE TITLE
Not working in Nether/End

### ISSUE THREAD

**Issue by MatthewXcap** [ps-dps/KeepSomeInventory#13]
I have this as a Datapack, and it only works in the Overworld, not the Nether or End. Please fix this.

**Comment by PuckiSilver** [comment]
Are you playing this on a PaperMC server? That software aggressively breaks data packs by removing many features data packs rely on.

If this is the case - no, I will not be fixing this.
If this is not the case - please provide more information, like, is it singleplayer or multiplayer? What mods/plugins/server software do you use alongside it or is it fully vanilla?

**Comment by PuckiSilver** [comment]
Closing this since no further information was provided.
