### ISSUE TITLE
the mod is broken?

### ISSUE THREAD

**Issue by DiamondBor** [ps-dps/KeepSomeInventory#15]
I'm using the 1.20.6 version of the mod. I died and lost everything except my fireworks; my tools, weapons, armor, & food weren't dropped where I died. All my fighting equipment was just removed from the world, not dropped, or put in my inventory.

**Comment by PuckiSilver** [comment]
Are your playing in singleplayer or multiplayer? Do you have other mods/plugins/data packs installed?

The pack never touches the items that should be kept at all, it internally uses the "KeepInventory" gamerule and only removes the items that should be dropped, so the equipment meant to be kept never leave your inventory.

**Comment by DiamondBor** [comment]
I'm using singleplayer, and I am using some other mods that add new content but don't modify any vanilla items, at least not any that I had in my inventory / items dropped on death

Here's how my inventory looked after I got my items back,
![image](https://github.com/ps-dps/KeepSomeInventory/assets/99621601/23d89ef8-3898-4ae5-80c6-4f041ba3ad47)

When I respawned, I only had my fireworks, the water buckets, the ender pearls, the stack of arrows, and _i think?_ my food.

**Comment by PuckiSilver** [comment]
So you kept some items but not all of the ones you were supposed to? But items still dropped where you died, just not all? That’s even more strange..

Can you tell me the items that behaved weirdly? Then I may be able to reproduce this in vanilla minecraft - but if this is just an incompatibility with a mod, I’m sorry but I won’t be fixing that then, many mods introduce incompatibilities and as a data pack developer it’s impossible to react to all of them.

**Comment by DiamondBor** [comment]
I had an elytra and a set of diamond armor equipped (except for the chestplate which was in my inventory), a mace, a trident, a bow, and a diamond sword, axe, pickaxe, and shovel.

**Comment by PuckiSilver** [comment]
I’ll see if I can re-create that in vanilla somehow - thanks for letting me know

**Comment by PuckiSilver** [comment]
I can not reproduce this:

Inventory before death
![image](https://github.com/ps-dps/KeepSomeInventory/assets/84644295/d6a92a0c-4652-48c8-899a-37317975f5a9)

Dropped items on ground
![image](https://github.com/ps-dps/KeepSomeInventory/assets/84644295/c2d97a73-56d3-4d76-8c1b-c1ad3843bb3d)

Inventory after collecting items
![image](https://github.com/ps-dps/KeepSomeInventory/assets/84644295/ae4e2341-7b28-449d-b30b-ce3e5a378105)

As I said, the pack **never** clears items that are not supposed to be cleared. This is most likely an incompatibility with other mods you have installed, this is not an issue with KeepSomeInventory and will therefore not be fixed, thanks for the report though!

**Comment by PuckiSilver** [comment]
Sorry, I was hasty, the bug was with enchanted items, it's been fixed in v1.4.2 and onward, sorry for the lost items and general inconvenience
