### ISSUE TITLE
Enchanted items are not kept or dropped

### ISSUE THREAD

**Issue by ATwest88** [ps-dps/KeepSomeInventory#16]
Playing with the newest version 1.4.1 of the datapack on 1.20.6, when items are enchanted they are not kept in the inventory or dropped on the ground.
Originally found the issue on 1.4.0 of the 1.20.6 fabric version but switched to 1.4.1 with the datapack in a new world in vanilla 1.20.6 and get the same issue.
![2024-05-11_23 15 40](https://github.com/ps-dps/KeepSomeInventory/assets/43663922/19bc1534-875f-4bab-805a-5b8b5159bbee)
^Enchanted elytra, pickaxe, and chestplate here
![2024-05-11_23 16 38](https://github.com/ps-dps/KeepSomeInventory/assets/43663922/ca745294-410e-4a17-a758-4f93f0d931e1)
^After death only unenchanted tools are kept
![2024-05-11_23 16 52](https://github.com/ps-dps/KeepSomeInventory/assets/43663922/0648b937-332a-425e-a240-1762f6ccb607)
^Enchanted items aren't on the ground either

**Comment by PuckiSilver** [comment]
Thanks for the report, I’ll look into that!
