### ISSUE TITLE
Dying in creative mode still makes you loose some Items

### ISSUE THREAD

**Issue by TheAyes** [ps-dps/KeepSomeInventory#17]
Sure this isn't much of a big deal considering you can't really die in creative mode. Yet I believe it's worth mentioning :)

To reproproduce:
 1. Be in creative mode
 2. Have some dropable items in your inventory
 3. Enter the command `/kill @s` or fall out of world
 4. The items are gone now
 
 
![image](https://github.com/ps-dps/KeepSomeInventory/assets/68541335/e91ebcee-5518-479e-84bf-b325b4e23daa)

**Comment by PuckiSilver** [comment]
Are they deleted? In the picture it looks like they drop as expected 🤔

I'll see if i can reproduce it in vanilla and fix it when appropriate 👍

**Comment by TheAyes** [comment]
Are vanilla items also dropped when in creative mode? If so then I might be mistaken.

**Comment by PuckiSilver** [comment]
Yes, items are dropped in creative mode unless you have the keepInventory gamerule turned on - but the KeepSomeInventory messes with that so this should be the intended behavior.

Thanks for reporting anyway :)
Have fun with the pack
