### ISSUE TITLE
 With XP drop enabled, xp is deleted but not dropped

### ISSUE THREAD

**Issue by OwOday** [ps-dps/KeepSomeInventory#18]
I am using universal graves, not sure if theres a conflict

**Comment by PuckiSilver** [comment]
Yes that is most likely the case, providing support for other data packs that mess with the death mechanic of minecraft is very hard or impossible

**Comment by OwOday** [comment]
Is there a way to get the xp into some sort of state where it wont despawn or get wiped on server restart?

**Comment by PuckiSilver** [comment]
You can make it keep the xp other than that, that doesn’t sound related to the pack, if you choose that the xp drops, it will spawn as an xp orb and if that despawns on server restart, then that’s probably an issue with your server

**Comment by OwOday** [comment]
I disabled it and there is still no drops either way

**Comment by OwOday** [comment]
disabled the different graves mods

**Comment by PuckiSilver** [comment]
What server software are you using?
What version of minecraft are you using?
What version of the pack are you using?
Any other data packs/mods/plugins?

**Comment by OwOday** [comment]
Heres the pack I'm working on, https://modrinth.com/modpack/shadow-witches-honey-gang/version/0.0.3.1

The server is fabric launcher 15.11 1.20.1 
minecraft is 1.20.1

**Comment by OwOday** [comment]
Please note graves is embedded but disabled

**Comment by PuckiSilver** [comment]
I don't think I can help you with this, the pack is made to work with vanilla minecraft and it is 100% a data pack underneath, making compatibility even harder to ensure.

One (or multiple) of these (hundreds? of) mods is incompatible with the data pack. Finding that mod would be a giant task and I can't even say if providing support/compatibility is even **possible** for me to implement.

I'm sorry but I don't think its really feasible to include the pack in a mod pack of that size, thanks for checking it out and considering it though.
