### ISSUE TITLE
Hi friend sorry to bother you about 1.20.4 empty backpack death drop stones....

### ISSUE THREAD

**Issue by fklscc** [ps-dps/KeepSomeInventory#20]
Hi friend sorry to disturb about the packet in 1.3.3 empty backpack death dropped a stone issue, will it be fixed and support 1.20.4, I found in 1.4.1 this issue fixed, but it does not support 1.20.4 version of the server. Will you support it later? I used a translation software to translate it. I'm sorry if I offended you

**Comment by PuckiSilver** [comment]
No, sorry, new version won't support minecraft version 1.20.4 or older since minecraft changed the item format.
