### ISSUE TITLE
Doesnt work for 1.21

### ISSUE THREAD

**Issue by timtijmen2** [ps-dps/KeepSomeInventory#21]
Mojang changed it so all folders like "functions" and "advancements" now dont have the "s" anymore. Like "function" and "advancement".

But after changing those myself, i have a problem where all enchanted armor and tools are deleted upon death. Not unechanted items.

**Comment by PuckiSilver** [comment]
Pretty sure [this line of code](https://github.com/ps-dps/KeepSomeInventory/blob/18de9456d0170794753d6d73eb97e36ceeaed2f3/src/data/ps-keep/modules/main.bolt#L106) is at fault, iirc it should be `"enchantments"` where it says `"enchantment"`, though not completely certain and not really enough time to look deeper into it.

If that is not the actual error, it’s definitely this line.

**Comment by timtijmen2** [comment]
Ive finally been able to test it myself but it just stoped working entirely...

**Comment by YodaDude2011** [comment]
Has there been any updates for when 1.21 will be supported?

**Comment by PuckiSilver** [comment]
1.21 rewrite has been released 🎉
