### ISSUE TITLE
Will 1.21 be supported

### ISSUE THREAD

**Issue by AbomiNathan96** [ps-dps/KeepSomeInventory#22]
just wondering

**Comment by PuckiSilver** [comment]
I started a rewrite [on this branch](https://github.com/ps-dps/KeepSomeInventory/tree/rewrite) which is almost complete, when I take the time to work on it next it should be finished and then I'll release it.

So yes - but no ETA

**Comment by AbomiNathan96** [comment]
thank you very much!

**Comment by PuckiSilver** [comment]
Oh yea, it’s released 🎉
