### ISSUE TITLE
[Question] Keep XP on death

### ISSUE THREAD

**Issue by WildFyr16** [ps-dps/KeepSomeInventory#24]
I want player to keep their XP when they die, how exactly do I enable this? I tried looking on the modrith page but I could not figure it out. I had keep XP enabled in essentials but this datapack seems to over right that

**Comment by PuckiSilver** [comment]
The config options were removed in 1.21, now you need to comment out/remove the last line in `data/pskeep2/function/die.mcfunction` when opening the jar/zip.

If you are in an older version you can use this command in chat:
`/function ps-keep:config`
And then configure the pack using the text-based-menu that appears in chat.

**Comment by WildFyr16** [comment]
Oh, alright thanks. Why where the config options removed?

**Comment by PuckiSilver** [comment]
The whole thing was rewritten from the ground up and providing the config options makes the code laggier and less organized. If mojang provided us with actual config files I would most likely reimplement those options.
