### ISSUE TITLE
Not working in the nether/end on modified servers

### ISSUE THREAD

**Issue by Ab3loth** [ps-dps/KeepSomeInventory#25]
For my server the datapack seems to work just fine in the overworld but doesn't function at all in the nether, doesn't seem like anyone has encountered this so I assume I've done something wrong, help would be appreciated.

Purpur server running a few datapacks and plugins this (should) be the only one affecting death

**Comment by PuckiSilver** [comment]
Yea, modded servers like Purpur break a lot of vanilla features and Keep Some Inventory was made for vanilla settings.
I can maybe look into making it work but I can neither give a guarantee nor an ETA.

**Comment by WildFyr16** [comment]
Yes, this also happens in the End. I assume it has something to do with the different dimensions. I feel like I remember fixing this once before on a old server I had, not sure though.

**Comment by letianpai-lpt** [comment]
"I encountered the same issue on my Paper server, but I found that simply setting the 'keepInventory' gamerule to true in the Nether made it effective. You can try setting the 'keepInventory' gamerule for different worlds."

**Comment by letianpai-lpt** [comment]
"I encountered the same issue on my Paper server, but I found that simply setting the 'keepInventory' gamerule to true in the Nether made it effective. You can try setting the 'keepInventory' gamerule for different worlds."

**Comment by PuckiSilver** [comment]
This is tracked in the now pinned Issue #13

**Comment by WildFyr16** [comment]
How to fix this on modified CraftBukkit and forked versions of CraftBukkit (Spigot, PaperMC, PurPur, etc.) Enter the Nether or End and run `/gamerule keepInventory true`. This will set the keepInventory gamerule to true in both these dimension. In CraftBukkit, the Nether and the End have their own distinct sets of gamerules. Hope this helps!
