### ISSUE TITLE
Experience levels dropped are more than what the player had

### ISSUE THREAD

**Issue by YodaDude2011** [ps-dps/KeepSomeInventory#26]
After dying with 34 XP levels, I went to my pile of dropped items and picked up 55 levels of XP. After dying several more times, the number of XP that is picked up by a player exponentially increases.

**Comment by PuckiSilver** [comment]
Thanks for letting me know, I’ll double check my calculation!

**Comment by sansmaeda** [comment]
I opened a pull request #27 that should fix this issue.

**Comment by PuckiSilver** [comment]
Published the fix by @sansmaeda (❤️) as v2.0.1
https://modrinth.com/datapack/keep-some-inventory/version/v2.0.1
