### ISSUE TITLE
Datapack does not work when dying in another dimension on Minecraft server 

### ISSUE THREAD

**Issue by Plantor07** [ps-dps/KeepSomeInventory#32]
I run a paper server which I added the datapack to and it works amazing in the overworld but in the nether it doesn’t save your items and your items fly everywhere

**Comment by PuckiSilver** [comment]
Yea, this is known and a problem with paper. See #13
You may be able to fix it by running `gamerule keepInventory true` in both the end and the nether (and all other dimensions)

**Comment by Plantor07** [comment]
Wait but wouldn’t running keep inventory just make the datapack obsolete

**Comment by PuckiSilver** [comment]
No, the data pack uses "keepInventory" on by default and does the "losing items and xp" itself, it's the only good way to achieve this using a data pack

**Comment by Plantor07** [comment]
Ok, thanks but I think I’m just going to switch servers from paper to fabric so that it works and I can run some performance enhancing mods on it too
