### ISSUE TITLE
Update Request

### ISSUE THREAD

**Issue by lBleyl** [ps-dps/KeepSomeInventory#33]
This mod is very good, my friends and I always use it. Could you update it to 1.21.3 or will it not be possible?

**Comment by PuckiSilver** [comment]
Thanks! Glad you like the pack!
It will get an update for 1.21.3 but I can't say when I'll find the time to update it, sorry.

**Comment by lBleyl** [comment]
that's enough, thank you!

**Comment by Katknapp** [comment]
1.21.4?   👀
