### ISSUE TITLE
Modded Items Don't Drop

### ISSUE THREAD

**Issue by Mouy07** [ps-dps/KeepSomeInventory#9]
Upon death, only vanilla items are dropped. All modded items remain in inventory. The reason for this is that the datapack uses a list of items that _do_ drop instead of a list of items that _don't_ drop. Since the list only contains vanilla items, only they are dropped.

My suggestion would be to use a don't-drop list. I'm not sure if this is feasible, but it would be a much more robust solution if possible. It would allow modded items to drop, as well as making updating the pack easier when vanilla Minecraft inevitably gets new items.

**Comment by PuckiSilver** [comment]
I can look into using a do-drop list instead

I didn't choose that before because of technical limitations but minecraft has gotten some new features and there might be a nice way to do it now

**Comment by PuckiSilver** [comment]
There is no good way to make a "keep" list instead of a "drop" list but this issue should be better since I'm using the #c tags convention to extend the list.
